name: Sauce Demo CI Tests on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    name: Run Test on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name : Run Sauce Demo Login Tests
        run: mvn clean test
        continue-on-error: true
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report
          path: target/allure-results/
      - name: Notify Slack on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_CHANNEL: new-channel  # Replace with your channel name
            SLACK_TITLE: "✅ CI Tests Passed"
            SLACK_MESSAGE: "All tests passed successfully on branch ${{ github.ref_name }}"
            SLACK_COLOR: good
            SLACK_FOOTER: "GitHub Actions CI/CD"
      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_CHANNEL: new-channel
            SLACK_TITLE: "❌ CI Tests Failed"
            SLACK_MESSAGE: "Tests failed on branch ${{ github.ref_name }}. Check logs for details."
            SLACK_COLOR: danger
            SLACK_FOOTER: "GitHub Actions CI/CD"
